# AlwaysShadow - a program for forcing Shadowplay's Instant Replay to stay on.
# Copyright (C) 2024 Aviv Edery.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CC:=gcc
CXX:=g++
PKG_CONFIG ?= pkg-config
BIN:=bin
SRC:=src
INCL:=include
RESRC:=resources
WHITELISTS:=whitelists
WHITELIST_BIN:=$(BIN)/Whitelist.txt
PROG:=$(BIN)/AlwaysShadow.exe
RELEASE:=$(BIN)/AlwaysShadow.zip
FLAGFILE:=$(BIN)/cflags.txt
TAGSFILE:=$(BIN)/tags.txt
VERSIONFILE:=version.txt
VERSIONBRANCH:=version

# Implement a fallback because I don't want gh to be a mandatory dependency for anything other than make release.
GITHUB_NAME_WITH_OWNER ?= Akunxin/AlwaysShadow-ShadowPlay_Patcher

YELLOW_FG:=$(shell tput setaf 3)
PURPLE_FG:=$(shell tput setaf 5)
CYAN_FG:=$(shell tput setaf 6)
NOCOLOR:=$(shell tput sgr0)

# Auto detect files we want to compile.
CFILES:=$(wildcard $(SRC)/*.c)
CPPFILES:=$(wildcard $(SRC)/*.cpp) $(wildcard $(SRC)/patcher/*.cpp)
RFILES:=$(wildcard $(RESRC)/*.rc)

OBJS += $(patsubst $(SRC)/%.c,$(BIN)/%.o,$(CFILES))
OBJS += $(patsubst $(SRC)/%.cpp,$(BIN)/%.o,$(CPPFILES))
PATCHER_OBJS:=$(patsubst $(SRC)/%.cpp,$(BIN)/%.o,$(wildcard $(SRC)/patcher/*.cpp))
OBJS += $(patsubst $(RESRC)/%.rc,$(BIN)/%.o,$(RFILES))

# Can't autodetect autogenerated files.
OBJS += $(BIN)/gen_tags.o

# Files generated by compiler for recompiling based on changed dependencies.
DEPENDS:=$(wildcard $(BIN)/*.d) $(wildcard $(BIN)/patcher/*.d)

# The style of commenting below may seem funny but there's a reason, it's so the alignment spacing doesn't make the output ugly.
# C compiler flags.
CFLAGS += -c #							Compile, duh.
CFLAGS += -std=gnu11 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -finput-charset=UTF-8
CFLAGS += -I $(INCL) #					Search for #includes in this folder.
CFLAGS += -Wall #						All warnings (minus the ones we'll subtract now).
CFLAGS += -Wno-unknown-pragmas #		For getting rid of warnings about regions in the code.
CFLAGS += -Wno-unused-function #		Some functions aren't used depending on #ifdefs.
CFLAGS += -fmacro-prefix-map=$(SRC)/= #	Makes it so in the logs only basenames of files are printed.
CFLAGS += -MMD -MP #					Generate *.d files, used for detecting if we need to recompile due to a change in included headers.
CFLAGS += -D CURL_STATICLIB #			Mandatory for statically linking curl.
CFLAGS += -D GITHUB_NAME_WITH_OWNER=\"$(GITHUB_NAME_WITH_OWNER)\" # 		For building links to the GitHub repo.
CFLAGS += -D VERSION_BRANCH_AND_FILE=\"$(VERSIONBRANCH)/$(VERSIONFILE)\" #	For downloading the latest version tag.

# Linker flags.
LFLAGS += -Wall #     All warnings.
LFLAGS += -mwindows # Makes it so when you run the program it doesn't open cmd.
LFLAGS += -static #   For static linking so people don't have problems (they've had a few).

# Libraries that we link.
LIBS += -lpthread #   For multithreading.
LIBS += -lwbemuuid #  For WMI to get the command line of processes. 
LIBS += -lole32 #     For COM to get the command line of processes.
LIBS += -loleaut32 #  For working with BSTRs.
LIBS += -luuid #      For FOLDERID_LocalAppData.
LIBS += -lshlwapi #   For path functions.
LIBS += -lwtsapi32 #  For remote-session and console notifications.
LIBS += -lcfgmgr32 #  For verifying physical keyboard/mouse device ancestry.
LIBS += -ltaskschd -ladvapi32 -lshell32 -luser32

# Static dependencies vary with the installed MSYS2 curl/regex versions.
LIBS += $(shell $(PKG_CONFIG) --libs --static regex libcurl)

# yes/no to unicode strings.
unicode = yes
ifeq ($(strip $(unicode)),yes)
	CFLAGS += -D UNICODE -D _UNICODE
endif

# yes/no to debug builds (grants instant log flushing mostly).
debug = no
ifeq ($(strip $(debug)),yes)
	CFLAGS += -D DEBUG_BUILD
endif

# If not empty, use this tag instead of downloading the latest one from curl (for debugging).
CXXFLAGS = $(filter-out -std=%,$(CFLAGS)) -std=c++20 -DNOMINMAX

latest_tag =
ifneq ($(strip $(latest_tag)),)
	CFLAGS += -D LATEST_TAG_OVERRIDE=\"$(latest_tag)\"
endif

# yes/no to high frequency polling for debugging.
highfreq = no
ifeq ($(strip $(debug)),yes)
	CFLAGS += -D HIGH_FREQUENCY_POLLING
endif

# Either auto or a space-separated list of tags to function as the list of tags which existed when this build was compiled.
tags = auto

# Which command to use for opening the logs. Will probably only ever use this default or "less".
view = tail -f

# If empty, use no whitelist in make run. If it's the name of a sample whitelist we have, use that. Else, generate a whitelist with these contents.
# Note: make won't let this variable be equal to spaces but not empty.
whitelist = 

# Print these variables.
PRINT_VARS += unicode
PRINT_VARS += debug
PRINT_VARS += tags
PRINT_VARS += latest_tag
PRINT_VARS += highfreq
PRINT_VARS += view
PRINT_VARS += whitelist
$(foreach var,$(PRINT_VARS),$(info $(shell printf "%s%-20s%s = %s\n" "$(YELLOW_FG)" "$(var)" "$(NOCOLOR)" "$($(var))")))

.PHONY: all test screenshots release release_pre_build publish run runx log whitelists write_flagfile write_tags clean help FORCE

# Makes a build. Order is important.
all: write_flagfile write_tags $(PROG) $(BIN)/patches.json

# Safe regression tests: do not toggle replay or change the current Windows session.
test: $(BIN)/recovery_test.exe $(BIN)/session_test.exe $(BIN)/physical_input_test.exe $(BIN)/fixer_test.exe $(BIN)/ui_test.exe $(BIN)/patcher_test.exe $(BIN)/patcher_bridge_test.exe
	$(BIN)/recovery_test.exe
	$(BIN)/session_test.exe
	$(BIN)/physical_input_test.exe
	$(BIN)/fixer_test.exe
	$(BIN)/ui_test.exe
	$(BIN)/patcher_test.exe
	$(BIN)/patcher_bridge_test.exe

$(BIN)/ui_test.exe: tests/ui_test.c $(SRC)/ui.c $(SRC)/tray_position.c $(INCL)/ui.h $(INCL)/Resource.h $(INCL)/protection_policy.h | $(BIN)
	$(CC) -std=c11 -Wall -Wextra -Werror -D UNICODE -D _UNICODE -I $(INCL) tests/ui_test.c $(SRC)/ui.c $(SRC)/tray_position.c -static -lshell32 -luser32 -o $@

$(BIN)/patcher_test.exe: tests/patcher_test.cpp $(PATCHER_OBJS) $(BIN)/cJSON.o | $(BIN)
	$(CXX) $(filter-out -c -MMD -MP,$(CXXFLAGS)) -I $(SRC)/patcher tests/patcher_test.cpp $(PATCHER_OBJS) $(BIN)/cJSON.o -static -ladvapi32 -luser32 -lpthread -o $@

$(BIN)/patcher_bridge_test.exe: tests/patcher_bridge_test.cpp $(SRC)/patcher_bridge.cpp $(INCL)/patcher.h $(PATCHER_OBJS) $(BIN)/cJSON.o | $(BIN)
	$(CXX) $(filter-out -c -MMD -MP,$(CXXFLAGS)) -I $(SRC) tests/patcher_bridge_test.cpp $(PATCHER_OBJS) $(BIN)/cJSON.o -static -ladvapi32 -luser32 -lpthread -o $@

$(BIN)/capture_ui.exe: tools/capture_ui.cpp $(BIN)/ui.o $(BIN)/tray_position.o $(BIN)/Resources.o | $(BIN)
	$(CXX) $(filter-out -c -MMD -MP,$(CXXFLAGS)) -municode tools/capture_ui.cpp $(BIN)/ui.o $(BIN)/tray_position.o $(BIN)/Resources.o -static -lgdiplus -lgdi32 -lshell32 -luser32 -o $@

# Requires an unlocked local Windows desktop. Captures only the tool's own UI.
screenshots: $(BIN)/capture_ui.exe
	mkdir -p docs/screenshots
	$(BIN)/capture_ui.exe en menu docs/screenshots/menu-en.png
	$(BIN)/capture_ui.exe zh menu docs/screenshots/menu-zh.png
	$(BIN)/capture_ui.exe en timer docs/screenshots/timer-en.png
	$(BIN)/capture_ui.exe zh timer docs/screenshots/timer-zh.png
	$(BIN)/capture_ui.exe en status docs/screenshots/status-en.png
	$(BIN)/capture_ui.exe zh status docs/screenshots/status-zh.png

$(BIN)/recovery_test.exe: tests/recovery_test.c $(SRC)/recovery.c $(INCL)/recovery.h | $(BIN)
	$(CC) -std=c11 -Wall -Wextra -Werror -I $(INCL) tests/recovery_test.c $(SRC)/recovery.c -o $@

$(BIN)/session_test.exe: tests/session_test.c $(SRC)/session.c $(INCL)/session.h | $(BIN)
	$(CC) -std=c11 -Wall -Wextra -Werror -I $(INCL) tests/session_test.c -o $@

$(BIN)/physical_input_test.exe: tests/physical_input_test.c $(SRC)/physical_input.c $(INCL)/physical_input.h $(INCL)/session.h | $(BIN)
	$(CC) -std=c11 -Wall -Wextra -Werror -D_WIN32_WINNT=0x0A00 -I $(INCL) tests/physical_input_test.c -o $@

$(BIN)/fixer_test.exe: tests/fixer_test.c $(SRC)/fixer.c $(SRC)/recovery.c $(SRC)/cJSON.c $(INCL)/*.h | $(BIN)
	$(CC) -std=gnu11 -Wall -Werror -Wno-unknown-pragmas -Wno-unused-function -D UNICODE -D _UNICODE -D CURL_STATICLIB -I $(INCL) tests/fixer_test.c $(SRC)/recovery.c $(SRC)/cJSON.c -static $(LIBS) -o $@

# Creates a release inside a zip and pushes it to GitHub.
release: clean release_pre_build all
	rm -f $(RELEASE)
	7z a -tzip $(RELEASE) ./$(PROG) ./$(BIN)/patches.json README.md README.zh-CN.md LICENSE docs
	gh release upload $$(./make_helpers.sh latest_release tagName) $(RELEASE)

	@echo "Release is ready as a draft. Go to GitHub, inspect it, run make publish when you're ready."

# Part of make release, do not run this directly. It's things we want to do before "all" (must create the new tag before "all" calls write_tags).
# Note: would've been nicer to put this in a make_helpers function but I kinda like that make quits if any commands fail.
release_pre_build:
	gh release list

	@if [[ "$$(./make_helpers.sh latest_release isDraft)" == true ]]; then\
		./make_helpers.sh confirm "Detected that the lastest release is already a draft. Delete it?" && gh release delete $$(./make_helpers.sh latest_release tagName);\
	fi

	@echo "REMINDER: usually tags are of the form 'v1.x', and titles are 'AlwaysShadow v1.x'"
	@echo "Prerelease no, draft YES ABSOLUTELY!"
	gh release create --draft --prerelease=false

	@[[ "$$(./make_helpers.sh latest_release tagName)" =~ ^v[0-9]+.[0-9]+$$ ]] || ./make_helpers.sh confirm "Tag is not of the form 'v<major>.<minor>'. Are you sure?"
	@[[ "$$(./make_helpers.sh latest_release name)" == "AlwaysShadow $$(./make_helpers.sh latest_release tagName)" ]] || ./make_helpers.sh confirm "Title is not of the form 'AlwaysShadow <tag>'. Are you sure?"

# Publishes a drafted release.
publish:
	[[ "$$(git branch --show-current)" != $(VERSIONBRANCH) ]]
	[[ "$$(./make_helpers.sh latest_release isDraft)" == true ]]

	# make_helpers.sh won't exist once we checkout branches so we need to store this now.
	$(eval TAG:=$(shell ./make_helpers.sh latest_release tagName))

	@./make_helpers.sh confirm "Release $(TAG) will be published. Are you sure?"
	@./make_helpers.sh confirm "Are you ABSOLUTELY sure?"

	git add .
	git stash
	git checkout -B $(VERSIONBRANCH) origin/$(VERSIONBRANCH)
	echo -n "$(TAG)" > $(VERSIONFILE)

	git add .
	git commit -m 'version $(TAG)'

	git checkout master
	git stash pop -q || true
	git restore --staged .

	gh release edit --draft=false $(TAG)
	git push origin $(VERSIONBRANCH) || { echo "****FAILED TO PUSH $(VERSIONFILE) AFTER PUBLISHING RELEASE. FIX THIS ASAP****"; false; }
	@echo "Success!"

# Writes CFLAGS to a file only if it's changed from the last run. We use this to recompile binaries when changing to/from debug builds.
# Important that this target isn't simply called $(FLAGFILE), that's a different target which we use.
write_flagfile: $(FLAGFILE)

$(FLAGFILE): FORCE | $(BIN)
	echo "$(CFLAGS) $(CXXFLAGS)" | ./make_helpers.sh write_if_diff $(FLAGFILE)

FORCE:

# Give the generated file its own rule so a fresh parallel build waits for it.
write_tags: $(TAGSFILE)

# Recompile gen_tags.c only when the known tags actually change.
# Offline builds keep the previous list or fall back to local Git tags.
ifeq ($(strip $(tags)),auto)
$(TAGSFILE): FORCE | $(BIN)
	./make_helpers.sh known_tags $(TAGSFILE) | ./make_helpers.sh write_if_diff $(TAGSFILE)
else
$(TAGSFILE): FORCE | $(BIN)
	printf '%s\n' $(tags) | ./make_helpers.sh write_if_diff $(TAGSFILE)
endif

# Compiles and runs. Output streams are redirected to a log.
run: all runx

# "Run exclusively". Same as run, but won't try to compile it.
# Also creates a whitelist in the bin folder, support both copying one of the sample files or creating one on the fly.
runx:
	if [[ -f "$(WHITELISTS)/$(whitelist)" ]]; then cp "$(WHITELISTS)/$(whitelist)" $(WHITELIST_BIN);\
	elif [[ "$(whitelist)" ]]; then echo -n "$(whitelist)" > $(WHITELIST_BIN);\
	else rm -f $(WHITELIST_BIN); fi
	$(PROG) & pid=$$!; ./make_helpers.sh confirm "Press Y when you're ready to kill it..." && kill $$pid

# View latest logs as they come.
log:
	$(view) "$$LOCALAPPDATA"/AlwaysShadow/output.log

# View which sample whitelists we have to choose from.
# Special treatment for "empty" because we can't grep it.
whitelists:
	@printf %s "$(PURPLE_FG)" empty "$(CYAN_FG)" : "$(NOCOLOR)"; printf "\n"
	@cd $(WHITELISTS); grep -E --color '' *

# Remove build outputs, including the nested engine objects. Keep runtime
# configuration, whitelist and registry settings across rebuilds.
clean:
	rm -f $(OBJS) $(DEPENDS) $(PROG) $(RELEASE) $(FLAGFILE) $(TAGSFILE) $(BIN)/gen_tags.c $(BIN)/*_test.exe $(BIN)/capture_ui.exe
	rmdir $(BIN)/patcher 2> /dev/null || true

include $(DEPENDS)

# The rules below do the actual job of compiling and linking all the different files. You'll probably never run them directly.

# Create the final exe.
$(PROG): $(OBJS)
	$(CXX) $(LFLAGS) $(OBJS) $(LIBS) -o $@

# Keep user-edited runtime configuration across rebuilds.
$(BIN)/patches.json: | $(BIN)
	cp patches.json $@

# Compile .c files.
$(BIN)/%.o: $(SRC)/%.c $(FLAGFILE) | $(BIN)
	$(CC) $(CFLAGS) -o $@ $<

$(BIN)/gen_tags.o: $(BIN)/gen_tags.c $(FLAGFILE) | $(BIN)
	$(CC) $(CFLAGS) -o $@ $(BIN)/gen_tags.c

$(BIN)/%.o: $(SRC)/%.cpp $(FLAGFILE) | $(BIN)
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -o $@ $<

# Compile .rc files.
# For .c files we are able to autogenerate dependency files, but for .rc files we can't so we'll just make it depend on all headers.
$(BIN)/%.o: */%.rc $(INCL)/*.h $(RESRC)/*.manifest | $(BIN)
	windres -Iinclude -Iresources -o $@ $<

# Autogenerated code.
# This adds the tag "tagName" to the list of tags, but there's no reason to care.
$(BIN)/gen_tags.c: $(TAGSFILE) | $(BIN)
	awk '\
		BEGIN	{ print "// AUTOGENERATED FILE. DO NOT MODIFY.";\
				  print "#include \"defines.h\"";\
				  print "const char *tags[] = {" }\
		1 		{ print "    \"" $$0 "\"," }\
		END 	{ print "};";\
				  print "const size_t tagsLen = _countof(tags);" }' $< > $@

# Need that bin folder.
$(BIN):
	mkdir -p $@
